# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risks',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risks',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
