# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_auto_20180204_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='RisksSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.CreateModel(
            name='RisksType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.TextField()),
            ],
            options={
                'ordering': ('Name',),
            },
        ),
        migrations.AlterModelOptions(
            name='risks',
            options={'ordering': ('Name',)},
        ),
        migrations.RemoveField(
            model_name='risks',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='risks',
            name='ndate',
        ),
        migrations.RemoveField(
            model_name='risks',
            name='title',
        ),
        migrations.AddField(
            model_name='riskstype',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.Risks'),
        ),
        migrations.AddField(
            model_name='riskssubtype',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.RisksType'),
        ),
    ]
