# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-04 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0003_auto_20180204_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='risks',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='riskssubtype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='riskstype',
            options={'ordering': ('id',)},
        ),
    ]
